// ============================================================================
// src/mmr_client/mod.rs - Multi-Chain MMR Light Client Module
// ============================================================================

//! Multi-Chain MMR Light Client Module
//!
//! ## Overview
//!
//! This module provides a complete SPV (Simplified Payment Verification) light
//! client implementation using Merkle Mountain Range (MMR) data structures.
//! It supports verification of multiple blockchain chains simultaneously:
//! - One beacon chain (coordination layer)
//! - Multiple shard chains (execution layers)
//!
//! ## Architecture
//!
//! ```text
//! MultiChainClient (Top-Level Coordinator)
//!   │
//!   ├─── BeaconChainHandler (Required, Single Instance)
//!   │      ├─── ChainState (tip, MMR root, chain weight)
//!   │      ├─── MMR proofs verification
//!   │      └─── Persistent storage
//!   │
//!   └─── ShardChainHandlers (Map: shard_id → handler)
//!          ├─── ShardChainHandler(0)
//!          │      ├─── ChainState
//!          │      ├─── Cross-shard tx tracking
//!          │      └─── Storage
//!          ├─── ShardChainHandler(1)
//!          └─── ShardChainHandler(N)
//! ```
//!
//! ## Three-Level Verification System
//!
//! The module implements a three-level verification system that balances
//! security requirements with bandwidth efficiency:
//!
//! ### Level 1: BeaconBlockData (229 bytes)
//! - **Always full verification**
//! - Contains all beacon consensus fields
//! - Used for beacon chain proofs
//! - Supports complete PoW verification
//!
//! ### Level 2: FullShardBlockData (~2,200 bytes)
//! - **Complete PoW verification capability**
//! - Contains beacon_header for hash recalculation
//! - Includes all merkle proofs
//! - Required for chain weight proofs
//! - Used for recent blocks (< 1000 deep)
//!
//! ### Level 3: LightShardBlockData (~194 bytes)
//! - **Optimized for historical data**
//! - Pre-calculated PoW hash stored
//! - Omits verification data (91% bandwidth savings)
//! - Cannot verify PoW (trusts stored hash)
//! - Used for historical blocks (> 1000 deep)
//!
//! ## Verification Strategies
//!
//! Three verification strategies control security vs. efficiency trade-offs:
//!
//! ### Full Strategy (Default)
//! - Verifies MMR structure for all blocks
//! - Accepts both Full and Light blocks
//! - Does not verify PoW for Light blocks
//! - **Use for**: Normal light client operation
//!
//! ### Light Strategy
//! - Only verifies MMR structure
//! - Skips all PoW verification
//! - Maximum efficiency
//! - **Use for**: After full validation, historical queries
//!
//! ### Paranoid Strategy
//! - Rejects Light blocks entirely
//! - Verifies PoW for every block
//! - Maximum security
//! - **Use for**: Initial sync, chain weight verification, auditing
//!
//! ## Batch / Range Inclusion Verification (RF-17)
//!
//! Production path: `WeightedMMRBatchProof::verify_with_anchor` and
//! `WeightedMMRRangeProof::verify_with_anchor` on types from `common::proofs`.
//! Proofs are generated by `WindowedWeightedMMR::prove_batch` / `prove_range`.
//!
//! Legacy `MMRBatchProof` / `MMRRangeProof` climb-and-descend verifiers were
//! removed in RF-17 Batch D (Jun 2026).
//!
//! ## Module Organization
//!
//! - **`mmr`**: Core MMR data structure with append/prove/verify operations
//! - **`proofs`**: Proof type definitions (batch, range, fork, weight, summary)
//! - **`verification`**: Proof verification algorithms with security strategies
//! - **`chain_handler`**: Generic chain state management (base class)
//! - **`beacon_handler`**: Beacon chain specific handler (epoch tracking)
//! - **`shard_handler`**: Shard chain specific handler (cross-shard txs)
//! - **`multi_chain_client`**: Top-level coordinator (network, peers, sync)
//! - **`storage`**: Persistent storage interfaces (in-memory, file, sqlite)
//! - **`protocol`**: Network protocol for requesting proofs from full nodes
//! - **`light_client_config`**: Configuration loading (genesis, checkpoints, peers)
//!
//! ## Usage Example: Basic Light Client
//!
//! ```rust,ignore
//! use mmr_client::{
//!     MultiChainClient, InMemoryStorage, BlockData,
//!     BeaconBlockData, FullShardBlockData, LightShardBlockData,
//! };
//!
//! #[tokio::main]
//! async fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     // 1. Create storage backend
//!     let storage = Box::new(InMemoryStorage::new());
//!     
//!     // 2. Create multi-chain client
//!     let mut client = MultiChainClient::new(storage);
//!     
//!     // 3. Initialize beacon chain with genesis
//!     let beacon_genesis = create_beacon_genesis();
//!     client.init_beacon_chain(beacon_genesis).await?;
//!     
//!     // 4. Add shard chains
//!     for shard_id in 0..3 {
//!         let shard_genesis = create_shard_genesis(shard_id);
//!         client.add_shard_chain(shard_id, shard_genesis).await?;
//!     }
//!     
//!     // 5. Sync from network (fetches proofs from full nodes)
//!     let beacon_summary = fetch_beacon_summary().await?;
//!     client.sync_beacon_from_summary(beacon_summary).await?;
//!     
//!     // 6. Query chain state
//!     let beacon_state = client.get_beacon_state().await?;
//!     println!("Beacon height: {}", beacon_state.height());
//!     
//!     Ok(())
//! }
//! # fn create_beacon_genesis() -> mmr_client::proofs::BlockData { todo!() }
//! # fn create_shard_genesis(id: u32) -> mmr_client::proofs::BlockData { todo!() }
//! # async fn fetch_beacon_summary() -> Result<mmr_client::proofs::MMRChainSummary, Box<dyn std::error::Error>> { todo!() }
//! ```
//!
//! ## Usage Example: Verification Strategies
//!
//! ```rust,ignore
//! use mmr_client::{
//!     verification::{
//!         verify_chain_weight_proof_with_strategy,
//!         VerificationStrategy,
//!     },
//!     proofs::{WeightedChainWeightProof, WeightedMMRRangeProof},
//! };
//!
//! async fn sync_with_security_levels() -> Result<(), Box<dyn std::error::Error>> {
//!     // Chain weight — Paranoid verifies PoW for all blocks
//!     let weight_proof = fetch_chain_weight_proof(0, 1000).await?;
//!     assert!(verify_chain_weight_proof_with_strategy(
//!         &weight_proof,
//!         VerificationStrategy::Paranoid,
//!         &genesis_block,
//!     ));
//!
//!     // Range inclusion — verify on the proof type directly
//!     let range_proof = fetch_range_proof(1000, 10000).await?;
//!     let anchor = genesis_config.bitcoin_anchor_hash;
//!     assert!(range_proof.verify_with_anchor(anchor));
//!
//!     Ok(())
//! }
//! ```
//!
//! ## Usage Example: Weighted Proof Verification
//!
//! ```rust,ignore
//! use mmr_client::proofs::{WeightedMMRBatchProof, WeightedMMRRangeProof};
//!
//! async fn verify_proofs(
//!     batch_proof: &WeightedMMRBatchProof,
//!     range_proof: &WeightedMMRRangeProof,
//!     anchor: [u8; 32],
//! ) -> Result<(), Box<dyn std::error::Error>> {
//!     assert!(batch_proof.verify_with_anchor(anchor));
//!     assert!(range_proof.verify_with_anchor(anchor));
//!     Ok(())
//! }
//! ```
//!
//! ## Usage Example: Cross-Chain Transaction Verification
//!
//! ```rust,ignore
//! use mmr_client::MultiChainClient;
//!
//! async fn verify_cross_shard_transaction(
//!     client: &MultiChainClient,
//!     tx_hash: [u8; 32],
//! ) -> Result<bool, String> {
//!     // 1. Track cross-shard transaction
//!     client.track_cross_chain_tx(tx_hash, 0, 1);
//!     
//!     // 2. Verify transaction in source shard
//!     let merkle_proof_src = fetch_tx_proof(0, tx_hash).await?;
//!     let verified_src = client.verify_transaction_in_shard(
//!         0,
//!         tx_hash,
//!         &merkle_proof_src,
//!         100, // block height
//!     ).await?;
//!     
//!     // 3. Check cross-chain status
//!     let status = client.get_cross_chain_status(&tx_hash);
//!     println!("Cross-chain status: {:?}", status);
//!     
//!     Ok(verified_src)
//! }
//! # async fn fetch_tx_proof(shard: u32, hash: [u8; 32]) -> Result<Vec<[u8; 32]>, String> { todo!() }
//! ```
//!
//! ## Security Guarantees
//!
//! ### Full Verification (Paranoid Strategy)
//! ✅ **Prevents**: Fake chains, altered transactions, invalid PoW
//! ✅ **Verifies**: All cryptographic proofs, PoW hashes, MMR structure
//! ✅ **Requires**: Full block data for all blocks
//! ⚠️ **Cost**: High bandwidth (~2,200 bytes/block for shards)
//!
//! ### Standard Verification (Full Strategy)
//! ✅ **Prevents**: Fake chains, altered transactions, MMR manipulation
//! ⚠️ **Trusts**: Pre-calculated PoW hashes in Light blocks
//! ✅ **Accepts**: Both Full and Light blocks
//! ⚠️ **Cost**: Medium bandwidth (mixed Full/Light blocks)
//!
//! ### Minimal Verification (Light Strategy)
//! ✅ **Prevents**: MMR manipulation
//! ⚠️ **Trusts**: All stored data (PoW hashes, difficulties, weights)
//! ✅ **Accepts**: All block types
//! ⚠️ **Cost**: Low bandwidth (~194 bytes/block for shards)
//!
//! **Recommendation**: Use Paranoid for initial sync and chain weight proofs,
//! then switch to Full for ongoing operation, and Light for historical queries.
//!
//! ## Bandwidth Optimization
//!
//! ### Example: Syncing 10,000 Shard Blocks
//!
//! | Strategy | Block Types | Bandwidth | Security |
//! |----------|-------------|-----------|----------|
//! | Paranoid | All Full | 22 MB | Maximum |
//! | Full | 1000 Full + 9000 Light | 3.95 MB | High |
//! | Light | All Light | 1.94 MB | Medium* |
//!
//! *Medium security assumes the pre-calculated PoW hashes are trusted
//!
//! ## Performance Comparison (v0.2.0 vs v0.1.x)
//!
//! ### Batch Proof Verification
//!
//! | Blocks | v0.1.x | v0.2.0 | Speedup | Time Saved |
//! |--------|--------|--------|---------|------------|
//! | 10 | 65 µs | 34 µs | 1.91x | 31 µs |
//! | 100 | 285 µs | 148 µs | 1.92x | 137 µs |
//! | 200 | 541 µs | 282 µs | 1.92x | 259 µs |
//!
//! ### Range Proof Verification
//!
//! | Blocks | v0.1.x | v0.2.0 | Speedup | Time Saved |
//! |--------|--------|--------|---------|------------|
//! | 10 | 108 µs | 59 µs | 1.82x | 49 µs |
//! | 100 | 547 µs | 253 µs | 2.17x | 294 µs |
//! | 200 | 1,094 µs | 506 µs | 2.16x | 588 µs |
//!
//! ### Real-World Impact
//!
//! **Light Client Syncing 10,000 Blocks (100-block proofs):**
//! - v0.1.x: 100 proofs × 547 µs = 54.7 ms
//! - v0.2.0: 100 proofs × 253 µs = 25.3 ms
//! - **Time Saved**: 29.4 ms (54% faster sync)
//!
//! **Daily Operations (100 new blocks per day):**
//! - v0.1.x: ~54.7 ms/day verification time
//! - v0.2.0: ~25.3 ms/day verification time
//! - **Time Saved**: 29.4 ms/day (54% less CPU)

// ============================================================================
// SUBMODULE DECLARATIONS
// ============================================================================

pub mod beacon_handler;
pub mod chain_handler;
pub mod light_client_config;
pub mod mmr_light;
pub mod weighted_mmr_light;
// pub mod mmr;
pub mod multi_chain_client;

pub mod filament_wallet;

#[cfg(feature = "full-node")]
pub mod filament_server;

#[cfg(feature = "full-node")]
pub mod filament_p2p;

/// Re-export of `common::proofs` for backward-compatible test imports.
///
/// Tests and downstream crates may import via `mmr_client::proofs::*`.
/// This is an alias; prefer importing from `common::proofs` in new code.
pub mod proofs {
    pub use common_types::common::proofs::*;
}
pub mod parallel_verifier;
pub mod proof_selector;
pub mod protocol;
pub mod shard_handler;
pub mod storage;
pub mod verification;

// ── Phase 10 — Filament wallet protocol (Tracks A–H) ─────────────────────────
pub mod invoice;
pub mod shisha_uri;
pub mod f2f;
pub mod f2f_crypto;
// ── Address Book (AB-1..AB-8) ─────────────────────────────────────────────────
pub mod contact_store;
pub mod watch_notify;

// ============================================================================
// MMR EXPORTS
// ============================================================================

/// Core MMR data structure
// pub use mmr::MMR;

/// MMR proof structure
// pub use mmr::MMRProof;

// PROOF TYPE EXPORTS
//
// Proof types are canonically defined in `common::proofs::types`.
// `mmr_client::proofs` is a re-export stub (`pub use common_types::common::proofs::*`).
// Consumers can import via `mmr_client::proofs::*` for backward compatibility,
// or directly from `common::proofs::*` (preferred).

// ============================================================================
// VERIFICATION EXPORTS (RF-17 Batch D, Jun 2026)
//
// Batch and range inclusion verify via `WeightedMMR*Proof::verify_with_anchor`.
// This module exports fork proof + chain-weight helpers only.
//
// ============================================================================

/// Verify fork proof
///
/// Fork proofs demonstrate that two chains diverge from a common ancestor.
/// Used for detecting and resolving chain reorganizations.
///
/// # Example
/// ```rust,ignore
/// use mmr_client::{verify_fork_proof, MMRForkProof};
///
/// if verify_fork_proof(&fork_proof) {
///     println!("Valid fork detected at height {}", fork_proof.fork_height);
/// }
/// ```
pub use verification::verify_fork_proof;

/// Verify fork proof with custom verification strategy
///
/// # Example
/// ```rust,ignore
/// use mmr_client::verification::{
///     verify_fork_proof_with_strategy, VerificationStrategy
/// };
///
/// // Paranoid verification for critical fork detection
/// let valid = verify_fork_proof_with_strategy(
///     &fork_proof, VerificationStrategy::Paranoid
/// );
/// ```
pub use verification::verify_fork_proof_with_strategy;

/// Verify chain weight proof
///
/// Chain weight proofs demonstrate the total cumulative difficulty of a chain,
/// used for determining the canonical chain in case of forks.
///
/// **IMPORTANT**: Chain weight proofs ALWAYS use Paranoid strategy internally
/// and reject Light blocks, as accurate weight calculation requires verifying
/// actual PoW difficulties, not trusting pre-calculated values.
///
// `verify_chain_weight_proof` / `verify_chain_weight_proof_with_strategy`
// (the vanilla, non-weighted `MMRChainWeightProof` verifier) dropped from
// this public packaging — zero real call sites anywhere in this crate
// (confirmed by grep; only ever mentioned in doc-comment examples above),
// and it's legacy/superseded by `WeightedChainWeightProof` below. Kept out
// rather than porting unused vanilla proof-verification code.

pub use verification::verify_weighted_chain_weight_proof;

// ============================================================================
// VERIFICATION UTILITY EXPORTS
// ============================================================================

/// Verification strategy enum (Full, Light, Paranoid)
pub use verification::VerificationStrategy;

/// Generic verification result (used by some verification functions)
pub use verification::VerificationResult;

/// Hash a pair of values (used in MMR construction)
///
/// Computes: SHA256(SHA256(left || right))
///
/// # Example
/// ```rust,ignore
/// use mmr_client::verification::hash_pair;
///
/// let parent = hash_pair(&left_child, &right_child);
/// ```
// pub use verification::hash_pair;

// ============================================================================
// CHAIN HANDLER EXPORTS
// ============================================================================

/// Generic chain handler interface
pub use chain_handler::ChainHandler;

/// Chain state structure
pub use chain_handler::ChainState;

/// Chain type enum (Beacon, Shard)
pub use chain_handler::ChainType;

// ============================================================================
// BEACON HANDLER EXPORTS
// ============================================================================

/// Beacon chain specific handler
pub use beacon_handler::BeaconChainHandler;

// From beacon_handler - add ShardParameters if you need it
pub use beacon_handler::ShardParameters;

// ============================================================================
// SHARD HANDLER EXPORTS
// ============================================================================

/// Shard chain specific handler
pub use shard_handler::ShardChainHandler;

/// Cross-chain transaction tracking
pub use shard_handler::{CrossShardTxInfo, CrossShardStatus};

// ============================================================================
// MULTI-CHAIN CLIENT EXPORTS
// ============================================================================

/// Multi-chain coordinator
pub use multi_chain_client::MultiChainClient;

/// Peer information
//pub use multi_chain_client::PeerInfo;

/// Peer capabilities
pub use multi_chain_client::PeerCapabilities;

/// Sync configuration
pub use multi_chain_client::SyncConfiguration;

/// Chain sync status
pub use multi_chain_client::ChainSyncStatus;

/// Sync mode enum
pub use multi_chain_client::SyncMode;

/// Client metrics
pub use multi_chain_client::ClientMetrics;

/// Cross-chain transaction status
pub use multi_chain_client::CrossChainStatus;

// ============================================================================
// STORAGE EXPORTS
// ============================================================================

/// Storage interface trait
pub use storage::LightClientStorage;

/// In-memory storage (for testing)
pub use storage::InMemoryStorage;

/// File-based storage
pub use storage::FileStorage;

/// Storage statistics
pub use storage::StorageStats;

// ============================================================================
// PROTOCOL EXPORTS
// ============================================================================

/// Light client request types
pub use protocol::LightClientRequest;

/// Light client response types
pub use protocol::LightClientResponse;

/// Protocol handler for full nodes
pub use protocol::LightClientProtocolHandler;

/// Chain interface for full nodes to implement
pub use protocol::ChainInterface;

// ============================================================================
// PROOF SELECTOR EXPORTS (v0.2.3)
// ============================================================================

/// Auto-detect whether a height set is better served by a range or batch proof.
pub use proof_selector::ProofSelector;

/// Result of `ProofSelector::analyze` — `Range { start, end }` or `Batch { heights }`.
pub use proof_selector::ProofStrategy;

/// Errors returned by `ProofSelector::analyze`.
pub use proof_selector::ProofSelectorError;

/// Diagnostic statistics from `ProofSelector::analyze_with_stats`.
pub use proof_selector::SelectorStats;

/// Default fill-density threshold (0.75) used when none is specified.
pub use proof_selector::DEFAULT_DENSITY_THRESHOLD;

// ============================================================================
// PARALLEL VERIFICATION EXPORTS (Item M)
// ============================================================================

/// Verify multiple `WeightedMMRBatchProof`s in parallel using rayon.
///
/// Below `PROOF_PARALLEL_THRESHOLD_BATCH` (32) proofs, falls back to sequential
/// verification on the caller's thread.  Returns a `Vec<bool>` preserving
/// input order.
///
/// # Example
/// ```rust,ignore
/// use mmr_client::parallel_verifier::verify_batch_proofs_parallel;
///
/// let items: Vec<_> = shard_proofs.iter().map(|(p, a)| (p, *a)).collect();
/// let results = verify_batch_proofs_parallel(&items);
/// assert!(results.iter().all(|&ok| ok), "all shard proofs must be valid");
/// ```
pub use parallel_verifier::verify_batch_proofs_parallel;

/// Verify multiple `WeightedMMRRangeProof`s in parallel using rayon.
pub use parallel_verifier::verify_range_proofs_parallel;

/// Threshold below which batch proof sequential verification is used (no rayon overhead).
pub use parallel_verifier::PROOF_PARALLEL_THRESHOLD_BATCH;

/// Threshold below which range proof sequential verification is used (no rayon overhead).
pub use parallel_verifier::PROOF_PARALLEL_THRESHOLD_RANGE;

/// Maximum thread count for the shared proof-verification pool.
pub use parallel_verifier::PROOF_MAX_THREADS;

// ============================================================================
// WEIGHTED MMR LIGHT EXPORTS
// ============================================================================

/// Lightweight weighted MMR for light-client verification.
///
/// Mirrors [`mmr_light::MMRLight`] but uses [`WeightedHash`] (224-bit hash +
/// 32-bit rBits cumulative difficulty) for peaks and the recent-block cache.
/// The MMR root returned by [`weighted_mmr_light::WeightedMMRLight::get_root`]
/// carries cumulative chain weight directly in its `rbits()` field.
pub use weighted_mmr_light::WeightedMMRLight;

/// Diagnostic statistics for a [`WeightedMMRLight`] cache.
pub use weighted_mmr_light::WeightedCacheStats;

// ============================================================================
// CONFIGURATION EXPORTS
// ============================================================================

/// Light client configuration
pub use light_client_config::FilamentBootstrapConfig;
#[allow(deprecated)]
pub use light_client_config::LightClientConfig;

/// Network genesis information
pub use light_client_config::NetworkGenesisInfo;

/// Sync settings
pub use light_client_config::SyncSettings;

/// Checkpoint configuration
pub use light_client_config::CheckpointConfig;

/// Peer configuration
pub use light_client_config::PeerConfig;

// ============================================================================
// BENEFITS OF THIS ARCHITECTURE
// ============================================================================

/*
## Design Principles

### 1. Clear Separation of Concerns
   - Each chain has its own handler (beacon vs shard)
   - Verification logic separate from state management
   - Storage abstracted behind trait interface
   - Protocol separate from verification

### 2. Type Safety
   - ChainType enum prevents mixing beacon/shard operations
   - BlockData enum enforces verification levels
   - Compile-time guarantees for chain-specific operations
   - Strategy pattern for verification modes

### 3. Scalability
   - Add new shards dynamically at runtime
   - Remove inactive shards to free resources
   - Each handler is independent (no cross-contamination)
   - Efficient bandwidth usage with Light blocks

### 4. Security Flexibility
   - Three verification strategies (Full/Light/Paranoid)
   - Automatic verification level detection
   - Special rules for consensus-critical proofs
   - Progressive security (Paranoid → Full → Light)

### 5. Performance (v0.2.0)
   - Optimized verification algorithms (1.82x - 2.17x faster)
   - Incremental peak bagging eliminates O(n·p) overhead
   - <1KB memory overhead for optimizations
   - Backward compatible with v0.1.x code

### 6. Testability
   - Test individual handlers in isolation
   - Mock multi-chain scenarios easily
   - Unit test chain-specific logic separately
   - Verification strategies testable independently
   - Legacy functions available for validation testing

### 7. Extensibility
   - Easy to add new chain types (e.g., auxiliary chains)
   - Plugin architecture for chain-specific features
   - Minimal changes to add new capabilities
   - New block data levels can be added

### 8. Maintainability
   - Code organized by responsibility
   - Clear boundaries between components
   - Comprehensive documentation
   - Easy to understand the system architecture

## Performance Characteristics (v0.2.0)

### Verification Costs

| Strategy | MMR Verification | PoW Verification | Cost per Block (v0.2.0) |
|----------|------------------|------------------|-------------------------|
| Paranoid | ✅ O(log n) | ✅ O(1) | ~3-4 ms |
| Full | ✅ O(log n) | ⚠️ Full blocks only | ~1-2 ms |
| Light | ✅ O(log n) | ❌ Skipped | ~0.5-1 ms |

*Note: v0.1.x costs were ~2x higher due to redundant peak bagging*

### Memory Usage

| Component | Size | Notes |
|-----------|------|-------|
| MMR (1000 blocks) | ~2 MB | Peaks + nodes |
| HybridMMRState | ~224 bytes | Additional for optimized verification |
| BeaconBlockData | 229 bytes | Per block |
| FullShardBlockData | ~2,200 bytes | Per block |
| LightShardBlockData | 194 bytes | Per block |
| ChainState cache | ~100 KB | Per chain (100 blocks) |

### Bandwidth Requirements

Initial sync (10,000 blocks):
- Paranoid: 22 MB per shard
- Full (mixed): 3.95 MB per shard
- Light: 1.94 MB per shard

Ongoing sync (100 blocks/day):
- Full blocks: 220 KB per shard/day
- Light blocks: 19.4 KB per shard/day

## Common Patterns

### Pattern 1: Progressive Verification
```rust,ignore
// Step 1: Paranoid verification for chain weight
verify_chain_weight_proof_with_strategy(&proof, VerificationStrategy::Paranoid, &genesis)?;

// Step 2: Range proofs — verify on the proof type
recent_range.verify_with_anchor(anchor)?;
old_range.verify_with_anchor(anchor)?;
```

### Pattern 2: Multi-Shard Coordination
```rust,ignore
// Initialize beacon
client.init_beacon_chain(beacon_genesis).await?;

// Add shards dynamically
for shard_id in active_shards {
    client.add_shard_chain(shard_id, shard_genesis).await?;
}

// Track cross-shard transaction
client.track_cross_chain_tx(tx_hash, source_shard, dest_shard);
```

### Pattern 3: Adaptive Chain-Weight Verification
```rust,ignore
let strategy = if initial_sync {
    VerificationStrategy::Paranoid
} else {
    VerificationStrategy::Full
};

verify_chain_weight_proof_with_strategy(&weight_proof, strategy, &genesis)?;
```

## Testing Strategy

### Unit Tests
- MMR operations (append, prove, verify)
- Proof verification with each strategy
- Block data conversions (Full → Light)
- Chain handler state management
- Optimized vs legacy verification comparison (v0.2.0)

### Integration Tests
- Multi-chain client coordination
- Cross-shard transaction tracking
- Storage persistence and loading
- Network protocol request/response
- Performance benchmarks (v0.1.x vs v0.2.0)

### Security Tests
- Paranoid mode rejects Light blocks
- Chain weight proofs reject Light blocks
- PoW verification in Paranoid mode
- MMR proof tampering detection

## Migration from Old Code

### Old (v0.1.x):
```rust,ignore
use mmr_core::MMR;
verify_batch_proof(&root, &leaves, &proof);
```

### New (production path):
```rust,ignore
use mmr_client::proofs::WeightedMMRBatchProof;

batch_proof.verify_with_anchor(anchor)?;
```

### Legacy Access (removed):
```rust,ignore
// verify_batch_proof / verify_range_proof removed in RF-17 Batch D (Jun 2026).
// Use WeightedMMR*Proof::verify_with_anchor instead.
```

## Future Enhancements

Potential additions:
- [ ] Compressed proof formats (zip/zstd)
- [ ] Proof caching and reuse
- [ ] Automatic strategy selection based on network conditions
- [ ] Adaptive block data levels based on age
- [ ] SQLite storage backend
- [ ] P2P proof exchange protocol
- [ ] Merkle proof extraction for transaction verification
- [ ] Light client committee for checkpoint validation
- [ ] Further optimization of fork and chain weight proofs (v0.3.0)
- [ ] Batch processing of multiple proofs
*/